fix(backend): Configure JWT Auth with RS256 and Env Validation using Auth0 (#35)
* fix(backend): organize project

* fix: update docker-compose manifest

* fix: add auth0 configuration files

diff --git a/backend/dockerfile b/backend/dockerfile
--- a/backend/dockerfile
+++ b/backend/dockerfile
@@ -1,12 +1,18 @@
-FROM node:20
+FROM node:20 AS base
 
 WORKDIR /app
-
-COPY package*.json ./
-RUN npm install
-
 COPY . .
+RUN npm install
+RUN npm run build || (echo "Build failed" && exit 1)
 
-RUN npm run build
+############################
+FROM base AS dev
+COPY --from=base /app/dist ./dist
+COPY --from=base /app/node_modules ./node_modules
+CMD ["npm", "run", "start:dev"]
 
+############################
+FROM base AS prod
+USER node
+COPY --from=base /app/dist ./dist
 CMD ["node", "dist/main.js"]
