fix: update docker-compose manifest

diff --git a/backend/dockerfile b/backend/dockerfile
--- a/backend/dockerfile
+++ b/backend/dockerfile
@@ -3,12 +3,12 @@ FROM node:20 AS base
 WORKDIR /app
 COPY . .
 RUN npm install
-RUN npm run build
+RUN npm run build || (echo "Build failed" && exit 1)
 
 ############################
 FROM base AS dev
-USER node
 COPY --from=base /app/dist ./dist
+COPY --from=base /app/node_modules ./node_modules
 CMD ["npm", "run", "start:dev"]
 
 ############################
